echo 'master DB'
docker exec -it master_db  mysql -uroot -ptoor -e 'use db;select * from DiskUsage  order by  id desc    limit 1;'
echo 'Slave 1h'
docker exec -it slave1  mysql -uroot -ptoor -e 'use db;select * from DiskUsage  order by  id desc    limit 1;'
echo 'Slave 6h'
docker exec -it slave2  mysql -uroot -ptoor -e 'use db;select * from DiskUsage  order by  id desc    limit 1;'
echo 'master-slave '
docker exec -it slave_15  mysql -uroot -ptoor -e 'use db;select * from DiskUsage  order by  id desc    limit 1;'
echo 'Slave 1 status'
#docker exec -it slave1  mysql -uroot -ptoor -e 'show slave status\G'
echo ' Master Slave  status'
docker exec -it slave_15  mysql -uroot -ptoor -e 'show slave status\G'
