version: '3.1'
services:

   slave15:
    image: mysql:5.7
    container_name: 'slave_15'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user12345'
      MYSQL_DATABASE: db
    ports:
      - 3311:3306
    volumes:
      - my-datavolume:/var/lib/mysq      
#      - ./conf.d:/etc/mysql/conf.d/
#      - mysqlconf:/etc/mysql/conf.d      
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./sql:/docker-entrypoint-initdb.d


volumes:
  my-datavolume:
  mysqlconf:
